### ISSUE TITLE
UseShed & UseCache Flags

### ISSUE THREAD

**Issue by doxthree** [GDATASoftwareAG/vaas#105]
In the VerdictRequest protocol you can specify two optional flags:
`use_shed` & `use_cache`

These are debug flags and should be documented and provided as example in all SDKs.

**Comment by secana** [comment]
Also, rename the `use_shed` to something different which describes what it is.

**Comment by secana** [comment]
Flags implemented and documented as "only available for some accounts" in:

- [ ] Rust
- [ ] Dotnet
- [ ] Java
- [ ] PHP
- [ ] Typescript
- [ ] Python

**Comment by secana** [comment]
@doxthree any progress on this one or is it not clear, if we need to implement it? I would rather keep the SDK simple and we decide how we protect the customer, instead of giving options.

**Comment by sfotiadis** [comment]
UseShed renamed to UseHashLookup in go SDK

**Comment by unglaublicherdude** [comment]
Pull Request for PHP is open.

**Comment by unglaublicherdude** [comment]
Python already had the feature

**Comment by unglaublicherdude** [comment]
Dotnet already had the feature

**Comment by unglaublicherdude** [comment]
@secana any chance you can implement the flags for rus? 🥺

**Comment by secana** [comment]
Sure. I'll have a look in the next few days.

**Comment by unglaublicherdude** [comment]
dunno why I closed this, the rust pr is open now
