### ISSUE TITLE
Add configurable timeout for Request against TokenEndpoint

### ISSUE THREAD

**Issue by doxthree** [GDATASoftwareAG/vaas#124]
When getting a token from a configurable or default token endpoint, a timeout can occur. 
In the most cases, the timeout varies in each SDK. Also, the timeout should be configurable, since customers can also use their own token endpoint.

Check if done:
- [ ] TypeScript
- [ ] PHP
- [ ] .NET
- [ ] Rust
- [ ] Python
- [ ] Java
- [ ] Javascript

**Comment by unglaublicherdude** [comment]
please split per language
