### ISSUE TITLE
Add examples for UrlScan

### ISSUE THREAD

**Issue by doxthree** [GDATASoftwareAG/vaas#150]
Besides the regular example for FileScan, there should be also examples for UrlScans for each SDKs.

Check if done:

- [x] TypeScript
- [x] PHP
- [x] .NET
- [x] Rust
- [x] Python
- [x] Java
- [x] Javascript

**Comment by secana** [comment]
I'm not sure how much sense it makes for `rust` to have a separate documentation as a `Readme.md` which needs to be kept up to date, if there is a compile time checked documentation which is always correct on [doc.rs - vaas](https://docs.rs/vaas/2.0.2/vaas/). Maybe just link to the docs in the readme?

**Comment by doxthree** [comment]
@secana I updated the lib.rs with the new authentication mechanism & add an url scan example.
