### ISSUE TITLE
TypeScript: The Upload is not working

### ISSUE THREAD

**Issue by unglaublicherdude** [GDATASoftwareAG/vaas#225]
For more infos, just look at the integration-tests.

**Comment by doxthree** [comment]
@unglaublicherdude [this commit](https://github.com/GDATASoftwareAG/vaas/commit/64ebc72ff1e9ad63b8e920caca9e5152248e1a29#diff-993c872f8b7c087772ebf5890b0d75749ba0afeb130fc33ff3b3812883e47c6d) just fixed this bug, so i will close this issue

btw. great job at finding this :+1:
