### ISSUE TITLE
Include ResourceOwnerPasswordGrantAuthenticator for SDK

### ISSUE THREAD

**Issue by doxthree** [GDATASoftwareAG/vaas#289]
- [x] Implement logic for using password and username as new Authenticator with example
- [x] Python
- [x] PHP
- [x] Dotnet
- [x] Java
- [x] Go
- [x] Ruby
- [x] Rust
- [x] TypeScript

**Comment by sfotiadis** [comment]
In this case, is it necessary to pass the client ID, or could it be better with a default value? I think it could be confusing for users since it's not immediately obvious which client ID to use.
