### ISSUE TITLE
Implement scan methods for streams

### ISSUE THREAD

**Issue by lennartdohmann** [GDATASoftwareAG/vaas#354]
Add a method to each SDK that allows to check for streams, similar to [Java's forInputStream](https://github.com/GDATASoftwareAG/vaas/blob/e9d91cb9f71cf51a264ac9c60c2b54b347288fdd/java/src/main/java/de/gdata/vaas/Vaas.java#L433) method.

- [x] Typescript
- [x] Go
- [x] Dotnet
- [x] Python
- [x] Rust
- [x] Ruby
- [x] PHP

In addition, tests and examples should be added in parallel to the existing ones in the examples folder.

**Comment by unglaublicherdude** [comment]
ruby still missing

**Comment by unglaublicherdude** [comment]
ruby will not be done
